### ISSUE TITLE
Installation and configuration question

### ISSUE THREAD

**Issue by merbauraya** [ihadeed/ng2-chartjs2#4]
Hello there, 
I'm new to angular/ionic and chartJs. I'm trying to use ng2-charts2 in Ionic2 but received the following error:
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in ./HelloIonicPage class HelloIonicPage - inline template:0:39
ORIGINAL EXCEPTION: ReferenceError: Chart is not defined
ORIGINAL STACKTRACE:
ReferenceError: Chart is not defined
    at ChartComponent.ngOnInit (http://localhost:8100/build/js/app.bundle.js:93865:26)
    at DebugAppView._View_HelloIonicPage0.detectChangesInternal (HelloIonicPage.template.js:65:83)
    at DebugAppView.AppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:31753:14)
    at DebugAppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:31858:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:8100/build/js/app.bundle.js:31779:19)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:8100/build/js/app.bundle.js:31764:14)
    at DebugAppView.AppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:31753:14)
    at DebugAppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:31858:44)
    at ViewRef_.detectChanges (http://localhost:8100/build/js/app.bundle.js:32210:65)
    at ViewController.fireWillEnter (http://localhost:8100/build/js/app.bundle.js:61826:22)

I suspected this could be just installation issue. I did the following:
- npm install ng2-chartjs2 --save
- npm install chart.js --save

in my ts file
import {ChartComponent, Chart} from 'ng2-chartjs2';

and use your example for data/label setting. Am i missing something here?

Thanks,

**Comment by merbauraya** [comment]
Nevermind. Got it working.
Looking forward to learn more/.

I put Chart.js in build/js folder and include it in index.html
 <script src="build/js/Chart.js"></script>

Thanks
